name: "Setup Bun Environment"
description: "Bunの環境セットアップ（mise、キャッシュ、install）"
runs:
  using: "composite"
  steps:
    # mise経由でBunの適切なバージョンをセットアップ
    - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3
    # Bunの依存関係キャッシュで高速化
    - name: Cache Bun dependencies
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-
    # 依存関係のインストール
    - run: bun install
      shell: bash
